pipeline {
    agent any

    // Optional: Define tools if you have them configured in Jenkins "Global Tool Configuration"
    // tools {
    //     maven 'Maven3' // Must match the name in your Jenkins config
    //     jdk 'Java11'   // Must match the name in your Jenkins config
    // }

    stages {
        stage('Checkout') {
            steps {
                // Pulls the latest code from your repository
                checkout scm
            }
        }

        stage('Compile') {
            steps {
                // Cleans the target directory and compiles the code using Java 11
                echo 'Compiling the project...'
                sh 'mvn clean compile' 
                // NOTE: If your Jenkins is hosted on Windows, change 'sh' to 'bat', e.g., bat 'mvn clean compile'
            }
        }

        stage('Run Functional Tests') {
            steps {
                // Runs Selenium/Rest-Assured/Cucumber tests via Surefire plugin
                // Using catchError ensures that even if tests fail, JMeter and Allure will still run
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    echo 'Running UI and API tests...'
                    sh 'mvn test'
                }
            }
        }

        stage('Run Performance Tests') {
            steps {
                // Executes the JMeter load_test.jmx files configured in your pom.xml
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    echo 'Running JMeter Load Tests...'
                    sh 'mvn jmeter:jmeter jmeter:results'
                }
            }
        }
    }

    post {
        always {
            echo 'Generating Reports and Archiving Artifacts...'
            
            // 1. Generate Allure Report
            // This requires the "Allure Plugin" to be installed on your Jenkins server
            allure([
                includeProperties: false,
                jdk: '',
                properties: [],
                reportBuildPolicy: 'ALWAYS',
                results: [[path: 'target/allure-results'], [path: 'allure-results']]
            ])
            
            // 2. Archive JMeter HTML reports (if generated by the plugin)
            archiveArtifacts artifacts: 'target/jmeter/reports/**', allowEmptyArchive: true
            
            // 3. Archive Cucumber/Surefire reports
            archiveArtifacts artifacts: 'target/surefire-reports/**', allowEmptyArchive: true
        }
        
        success {
            echo 'Build and Tests completed successfully!'
        }
        
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}